---
title: boolean
categories: [ "Variables" ]
subCategories: [ "Data Types" ]
---

:source-highlighter: pygments
:pygments-style: arduino



= boolean


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Description
A `boolean` holds one of two values, link:../true[true] or link:../false[false]. (Each boolean variable occupies one byte of memory.)


[%hardbreaks]

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Example Code
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄
The code shows how to use `boolean` datatype.

[source,arduino]
----
int LEDpin = 5;       // LED on pin 5
int switchPin = 13;   // momentary switch on 13, other side connected to ground

boolean running = false;

void setup()
{
  pinMode(LEDpin, OUTPUT);
  pinMode(switchPin, INPUT);
  digitalWrite(switchPin, HIGH);      // turn on pullup resistor
}

void loop()
{
  if (digitalRead(switchPin) == LOW)
  {  // switch is pressed - pullup keeps pin high normally
    delay(100);                        // delay to debounce switch
    running = !running;                // toggle running variable
    digitalWrite(LEDpin, running)      // indicate via LED
  }
}
----
[%hardbreaks]

[float]
=== See also
// Link relevant content by category, such as other Reference terms (please add the tag #LANGUAGE#),
// definitions (please add the tag #DEFINITION#), and examples of Projects and Tutorials
// (please add the tag #EXAMPLE#)  ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄

[role="definition"]
* #DEFINITION# link:../constants[constants] +
* #DEFINITION# link:../boolean[boolean operators] +
* #DEFINITION# link:../../variableDeclaration[Variable Declaration]

--
// HOW TO USE SECTION ENDS
