:source-highlighter: pygments
:pygments-style: arduino
:ext-relative: adoc


= char


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Description
A data type that takes up 1 byte of memory that stores a character value. Character literals are written in single quotes, like this: 'A' (for multiple characters - strings - use double quotes: "ABC").

Characters are stored as numbers however. You can see the specific encoding in the link:ASCIIchart{ext-relative}[ASCII chart]. This means that it is possible to do arithmetic on characters, in which the ASCII value of the character is used (e.g. 'A' + 1 has the value 66, since the ASCII value of the capital letter A is 65). See link:println{ext-relative}[`Serial.println`] reference for more on how characters are translated to numbers.

The char datatype is a signed type, meaning that it encodes numbers from -128 to 127. For an unsigned, one-byte (8 bit) data type, use the _byte_ data type.
[%hardbreaks]

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Example Code
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄


[source,arduino]
----
  char myChar = 'A';
  char myChar = 65;      // both are equivalent
----
[%hardbreaks]



[float]
=== See also
// Link relevant content by category, such as other Reference terms (please add the tag #LANGUAGE#),
// definitions (please add the tag #DEFINITION#), and examples of Projects and Tutorials
// (please add the tag #EXAMPLE#)  ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄
[role="definition"]
* #DEFINITION# link:byte{ext-relative}[byte] +
* #DEFINITION# link:int{ext-relative}[int] +
* #DEFINITION# link:array{ext-relative}[array]

[role="language"]
* #LANGUAGE# link:println{ext-relative}[Serial.println]

--
// HOW TO USE SECTION ENDS
