---
title: double
categories: [ "Variables" ]
subCategories: [ "Data Types" ]
---

:source-highlighter: pygments
:pygments-style: arduino



= double


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Description
Double precision floating point number. On the Uno and other ATMEGA based boards, this occupies 4 bytes. That is, the double implementation is exactly the same as the float, with no gain in precision.

On the Arduino Due, doubles have 8-byte (64 bit) precision.
[%hardbreaks]

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--


[float]
=== Notes and Warnings
Users who borrow code from other sources that includes double variables may wish to examine the code to see if the implied precision is different from that actually achieved on ATMEGA based Arduinos.
[%hardbreaks]

[float]
=== See also
// Link relevant content by category, such as other Reference terms (please add the tag #LANGUAGE#),
// definitions (please add the tag #DEFINITION#), and examples of Projects and Tutorials
// (please add the tag #EXAMPLE#)  ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄
[role="definition"]
* #DEFINITION# link:../float[float]

--
// HOW TO USE SECTION ENDS
