---
title: int
categories: [ "Variables" ]
subCategories: [ "Data Types" ]
---

:source-highlighter: pygments
:pygments-style: arduino



= int


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Description
Integers are your primary data-type for number storage.

On the Arduino Uno (and other ATMega based boards) an int stores a 16-bit (2-byte) value. This yields a range of -32,768 to 32,767 (minimum value of -2^15 and a maximum value of (2^15) - 1).
On the Arduino Due, an int stores a 32-bit (4-byte) value. This yields a range of -2,147,483,648 to 2,147,483,647 (minimum value of -2^31 and a maximum value of (2^31) - 1).

int's store negative numbers with a technique called (http://en.wikipedia.org/wiki/2%27s_complement[2's complement math]). The highest bit, sometimes referred to as the "sign" bit, flags the number as a negative number. The rest of the bits are inverted and 1 is added.

The Arduino takes care of dealing with negative numbers for you, so that arithmetic operations work transparently in the expected manner. There can be an unexpected complication in dealing with the link:../../structure/bitwise-operators/bitshiftRight[bitshift right operator] (>>) however.
[%hardbreaks]


[float]
=== Syntax
`int var = val;`

`var` - your int variable name +
`val` - the value you assign to that variable

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Example Code
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄


[source,arduino]
----
  int ledPin = 13;
----
[%hardbreaks]

[float]
=== Notes and Warnings
When variables are made to exceed their maximum capacity they "roll over" back to their minimum capacity, note that this happens in both directions.
[source,arduino]
----
int x;
   x = -32768;
   x = x - 1;       // x now contains 32,767 - rolls over in neg. direction

   x = 32767;
   x = x + 1;       // x now contains -32,768 - rolls over

----
[%hardbreaks]

[float]
=== See also
// Link relevant content by category, such as other Reference terms (please add the tag #LANGUAGE#),
// definitions (please add the tag #DEFINITION#), and examples of Projects and Tutorials
// (please add the tag #EXAMPLE#)  ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄
[role="definition"]
* #DEFINITION# link:../byte[byte] +
* #DEFINITION# link:../unsignedInt[unsigned int] +
* #DEFINITION# link:../long[long] +
* #DEFINITION# link:../unsignedLong[unsigned long] +
* #DEFINITION# link:../../constants/integerConstants[Integer Constants] +
* #DEFINITION# link:../../variableDeclaration[Variable Declaration]
--
// HOW TO USE SECTION ENDS
