---
title: int
categories: [ "Variables" ]
subCategories: [ "Data Types" ]
---





= int


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Description
Integers are your primary data-type for number storage.

On the Arduino Uno (and other ATmega based boards) an int stores a 16-bit (2-byte) value. This yields a range of -32,768 to 32,767 (minimum value of -2^15 and a maximum value of (2^15) - 1).
On the Arduino Due and SAMD based boards (like MKR1000 and Zero), an int stores a 32-bit (4-byte) value. This yields a range of -2,147,483,648 to 2,147,483,647 (minimum value of -2^31 and a maximum value of (2^31) - 1).

int's store negative numbers with a technique called (http://en.wikipedia.org/wiki/2%27s_complement[2's complement math]). The highest bit, sometimes referred to as the "sign" bit, flags the number as a negative number. The rest of the bits are inverted and 1 is added.

The Arduino takes care of dealing with negative numbers for you, so that arithmetic operations work transparently in the expected manner. There can be an unexpected complication in dealing with the link:../../../structure/bitwise-operators/bitshiftright/[bitshift right operator] (>>) however.
[%hardbreaks]


[float]
=== Syntax
`int var = val;`

`var` - your int variable name +
`val` - the value you assign to that variable

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Example Code
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄


[source,arduino]
----
  int ledPin = 13;
----
[%hardbreaks]

[float]
=== Notes and Warnings
When signed variables are made to exceed their maximum or minimum capacity they _overflow_.  The result of an overflow is unpredictable so this should be avoided.  A typical symptom of an overflow is the variable "rolling over" from its maximum capacity to its minimum or vice versa, but this is not always the case.  If you want this behavior, use link:../unsignedint/[unsigned int].


--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION STARTS
[#see_also]
--

[float]
=== See also

[role="language"]
* #LANGUAGE# link:../../constants/integerconstants[Integer Constants]

--
// SEE ALSO SECTION ENDS
