---
title: "String()"
categories: [ "Variables" ]
subCategories: [ "Data Types" ]
---





= String()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Description
Constructs an instance of the String class. There are multiple versions that construct Strings from different data types (i.e. format them as sequences of characters), including:

* a constant string of characters, in double quotes (i.e. a char array)
* a single constant character, in single quotes
* another instance of the String object
* a constant integer or long integer
* a constant integer or long integer, using a specified base
* an integer or long integer variable
* an integer or long integer variable, using a specified base
* a float or double, using a specified decimal palces

Constructing a String from a number results in a string that contains the ASCII representation of that number. The default is base ten, so
[source,arduino]
----
String thisString = String(13);
----
gives you the String "13". You can use other bases, however. For example,


[source,arduino]
----
String thisString = String(13, HEX);
----

gives you the String "D", which is the hexadecimal representation of the decimal value 13. Or if you prefer binary,

[source,arduino]
----
String thisString = String(13, BIN);
----

gives you the String "1101", which is the binary representation of 13.
[%hardbreaks]


[float]
=== Syntax
[source,arduino]
----
String(val)
String(val, base)
String(val, decimalPlaces)
----

[float]
=== Parameters
`val`:  a variable to format as a String - *Allowed data types:* string, char, byte, int, long, unsigned int, unsigned long, float, double +
`base` (optional): the base in which to format an integral value
`decimalPlaces` (*only if val is float or double*): the desired decimal places

[float]
=== Returns
an instance of the String class.

--
// OVERVIEW SECTION ENDS



// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Example Code
All of the following are valid declarations for Strings.
[source,arduino]
----
String stringOne = "Hello String";                                     // using a constant String
String stringOne =  String('a');                                          // converting a constant char into a String
String stringTwo =  String("This is a string");                 // converting a constant string into a String object
String stringOne =  String(stringTwo + " with more"); // concatenating two strings
String stringOne =  String(13);                                          // using a constant integer
String stringOne =  String(analogRead(0), DEC);          // using an int and a base
String stringOne =  String(45, HEX);                                // using an int and a base (hexadecimal)
String stringOne =  String(255, BIN);                               // using an int and a base (binary)
String stringOne =  String(millis(), DEC);                        // using a long and a base
String stringOne =  String(5.698, 3);                                // using a float and the decimal places
----

--
// HOW TO USE SECTION ENDS


[float]
=== Functions

[role="language"]
* #LANGUAGE# link:../string/functions/charat[charAt()]
* #LANGUAGE# link:../string/functions/compareto[compareTo()]
* #LANGUAGE# link:../string/functions/concat[concat()]
* #LANGUAGE# link:../string/functions/c_str[c_str()]
* #LANGUAGE# link:../string/functions/endswith[endsWith()]
* #LANGUAGE# link:../string/functions/equals[equals()]
* #LANGUAGE# link:../string/functions/equalsignorecase[equalsIgnoreCase()]
* #LANGUAGE# link:../string/functions/getbytes[getBytes()]
* #LANGUAGE# link:../string/functions/indexof[indexOf()]
* #LANGUAGE# link:../string/functions/lastindexof[lastIndexOf()]
* #LANGUAGE# link:../string/functions/length[length()]
* #LANGUAGE# link:../string/functions/remove[remove()]
* #LANGUAGE# link:../string/functions/replace[replace()]
* #LANGUAGE# link:../string/functions/reserve[reserve()]
* #LANGUAGE# link:../string/functions/setcharat[setCharAt()]
* #LANGUAGE# link:../string/functions/startswith[startsWith()]
* #LANGUAGE# link:../string/functions/substring[substring()]
* #LANGUAGE# link:../string/functions/tochararray[toCharArray()]
* #LANGUAGE# link:../string/functions/toint[toInt()]
* #LANGUAGE# link:../string/functions/tofloat[toFloat()]
* #LANGUAGE# link:../string/functions/tolowercase[toLowerCase()]
* #LANGUAGE# link:../string/functions/touppercase[toUpperCase()]
* #LANGUAGE# link:../string/functions/trim[trim()]

[float]
=== Operators

[role="language"]
* #LANGUAGE# link:../string/operators/elementaccess[[\] (element access)]
* #LANGUAGE# link:../string/operators/concatenation[+ (concatenation)]
* #LANGUAGE# link:../string/operators/append[+= (append)]
* #LANGUAGE# link:../string/operators/comparison[== (comparison)]
* #LANGUAGE# link:../string/operators/greaterthan[> (greater than)]
* #LANGUAGE# link:../string/operators/greaterthanorequalto[>= (greater than or equal to)]
* #LANGUAGE# link:../string/operators/lessthan[< (less than)]
* #LANGUAGE# link:../string/operators/lessthanorequalto[\<= (less than or equal to)]
* #LANGUAGE# link:../string/operators/differentfrom[!= (different from)]

[role="example"]
* #EXAMPLE# link: https://www.arduino.cc/en/Tutorial/BuiltInExamples#strings[Built-in String Tutorials]


// SEE ALSO SECTION STARTS
[#see_also]
--

[float]
=== See also

[role="language"]

--
// SEE ALSO SECTION ENDS
