---
title: String
categories: [ "Variables" ]
subCategories: [ "Data Types" ]
---





= string


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Description
Text Strings can be represented in two ways. you can use the String data type, which is part of the core as of version 0019, or you can make a String out of an array of type char and null-terminate it. This page described the latter method. For more details on the String object, which gives you more functionality at the cost of more memory, see the link:../stringobject[String object] page.
[%hardbreaks]

[float]
=== Syntax
All of the following are valid declarations for Strings.

`char Str1[15];` +
`char Str2[8] = {'a', 'r', 'd', 'u', 'i', 'n', 'o'};` +
`char Str3[8] = {'a', 'r', 'd', 'u', 'i', 'n', 'o', '\0'};` +
`char Str4[ ] = "arduino";` +
`char Str5[8] = "arduino";` +
`char Str6[15] = "arduino";`

*Possibilities for declaring Strings*

* Declare an array of chars without initializing it as in Str1
* Declare an array of chars (with one extra char) and the compiler will add the required null character, as in Str2
* Explicitly add the null character, Str3
* Initialize with a String constant in quotation marks; the compiler will size the array to fit the String constant and a terminating null character, Str4
* Initialize the array with an explicit size and String constant, Str5
* Initialize the array, leaving extra space for a larger String, Str6

*Null termination*

Generally, Strings are terminated with a null character (ASCII code 0). This allows functions (like `Serial.print()`) to tell where the end of a String is. Otherwise, they would continue reading subsequent bytes of memory that aren't actually part of the String.

This means that your String needs to have space for one more character than the text you want it to contain. That is why Str2 and Str5 need to be eight characters, even though "arduino" is only seven - the last position is automatically filled with a null character. Str4 will be automatically sized to eight characters, one for the extra null. In Str3, we've explicitly included the null character (written '\0') ourselves.

Note that it's possible to have a String without a final null character (e.g. if you had specified the length of Str2 as seven instead of eight). This will break most functions that use Strings, so you shouldn't do it intentionally. If you notice something behaving strangely (operating on characters not in the String), however, this could be the problem.

*Single quotes or double quotes?*

Strings are always defined inside double quotes ("Abc") and characters are always defined inside single quotes('A').

*Wrapping long Strings*

You can wrap long Strings like this:

[source,arduino]
----
char myString[] = "This is the first line"
" this is the second line"
" etcetera";
----

*Arrays of Strings*

It is often convenient, when working with large amounts of text, such as a project with an LCD display, to setup an array of Strings. Because Strings themselves are arrays, this is in actually an example of a two-dimensional array.

In the code below, the asterisk after the datatype `char` "`char*`" indicates that this is an array of "`pointers`". All array names are actually pointers, so this is required to make an array of arrays. Pointers are one of the more esoteric parts of C for beginners to understand, but it isn't necessary to understand pointers in detail to use them effectively here.

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Example Code
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄


[source,arduino]
----
char* myStrings[]={"This is String 1", "This is String 2", "This is String 3",
"This is String 4", "This is String 5","This is String 6"};

void setup(){
Serial.begin(9600);
}

void loop(){
for (int i = 0; i < 6; i++){
   Serial.println(myStrings[i]);
   delay(500);
   }
}
----


--
// HOW TO USE SECTION ENDS

// SEE ALSO SECTION STARTS
[#see_also]
--

[float]
=== See also

[role="language"]
* #LANGUAGE# link:../../utilities/progmem[PROGMEM]

--
// SEE ALSO SECTION ENDS
