---
title: analogReference()
categories: [ "Functions" ]
subCategories: [ "Analog I/O" ]
---


//


= analogReference()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Description
Configures the reference voltage used for analog input (i.e. the value used as the top of the input range). The options are:

Arduino AVR Boards (Uno, Mega, etc.)

* DEFAULT: the default analog reference of 5 volts (on 5V Arduino boards) or 3.3 volts (on 3.3V Arduino boards)
* INTERNAL: an built-in reference, equal to 1.1 volts on the ATmega168 or ATmega328P and 2.56 volts on the ATmega8 (not available on the Arduino Mega)
* INTERNAL1V1: a built-in 1.1V reference (Arduino Mega only)
* INTERNAL2V56: a built-in 2.56V reference (Arduino Mega only)
* EXTERNAL: the voltage applied to the AREF pin (0 to 5V only) is used as the reference.

Arduino SAMD Boards (Zero, etc.)

* AR_DEFAULT: the default analog reference of 3.3V
* AR_INTERNAL: a built-in 2.23V reference
* AR_INTERNAL1V0: a built-in 1.0V reference
* AR_INTERNAL1V65: a built-in 1.65V reference
* AR_INTERNAL2V23: a built-in 2.23V reference
* AR_EXTERNAL: the voltage applied to the AREF pin is used as the reference

Arduino SAM Boards (Due)

* AR_DEFAULT: the default analog reference of 3.3V. This is the only supported option for the Due.

[%hardbreaks]


[float]
=== Syntax
`analogReference(type)`


[float]
=== Parameters
`type`: which type of reference to use (see list of options in the description).

[float]
=== Returns
Nothing

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Notes and Warnings
After changing the analog reference, the first few readings from `analogRead()` may not be accurate.

*Don't use anything less than 0V or more than 5V for external reference voltage on the AREF pin! If you're using an external reference on the AREF pin, you must set the analog reference to EXTERNAL before calling `analogRead()`.* Otherwise, you will short together the active reference voltage (internally generated) and the AREF pin, possibly damaging the microcontroller on your Arduino board.

Alternatively, you can connect the external reference voltage to the AREF pin through a 5K resistor, allowing you to switch between external and internal reference voltages. Note that the resistor will alter the voltage that gets used as the reference because there is an internal 32K resistor on the AREF pin. The two act as a voltage divider, so, for example, 2.5V applied through the resistor will yield 2.5 * 32 / (32 + 5) = ~2.2V at the AREF pin.
[%hardbreaks]

--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== See also

[role="example"]
* #EXAMPLE# http://arduino.cc/en/Tutorial/AnalogInputPins[Description of analog input pins]

--
// SEE ALSO SECTION ENDS
