---
title: max()
categories: [ "Functions" ]
subCategories: [ "Math" ]
---





= max(x, y)


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Description
Calculates the maximum of two numbers.
[%hardbreaks]


[float]
=== Syntax
`max(x, y)`


[float]
=== Parameters
`x`: the first number, any data type
`y`: the second number, any data type

[float]
=== Returns
The larger of the two parameter values.

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Example Code
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄
The code ensures that sensVal is at least 20.

[source,arduino]
----
sensVal = max(sensVal, 20); // assigns sensVal to the larger of sensVal or 20
                           // (effectively ensuring that it is at least 20)
----
[%hardbreaks]

[float]
=== Notes and Warnings
Perhaps counter-intuitively, `max()` is often used to constrain the lower end of a variable's range, while `min()` is used to constrain the upper end of the range.

Because of the way the `max()` function is implemented, avoid using other functions inside the brackets, it may lead to incorrect results
[source,arduino]
----
max(a--, 0);   // avoid this - yields incorrect results

max(a, 0);           // use this instead -
a--;     // keep other math outside the function
----

--
// HOW TO USE SECTION ENDS
