---
title: pow()
categories: [ "Functions" ]
subCategories: [ "Math" ]
---





= pow(base, exponent)


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Description
Calculates the value of a number raised to a power. `Pow()` can be used to raise a number to a fractional power. This is useful for generating exponential mapping of values or curves.
[%hardbreaks]


[float]
=== Syntax
`pow(base, exponent)`


[float]
=== Parameters
`base`: the number (`float`)

`exponent`: the power to which the base is raised (`float`)

[float]
=== Returns
The result of the exponentiation. (`double`)

--
// OVERVIEW SECTION ENDS


// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Example Code
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄
See the (http://arduino.cc/playground/Main/Fscale[fscale]) function in the code library.

--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== See also

[role="definition"]
* #DEFINITION# link:../../../variables/data-types/float[float]
* #DEFENITION# link:../../../variables/data-types/double[double]

--
// SEE ALSO SECTION ENDS
