:source-highlighter: pygments
:pygments-style: arduino



= Mouse.isPressed()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Description
Checks the current status of all mouse buttons, and reports if any are pressed or not.
[%hardbreaks]


[float]
=== Syntax
`Mouse.isPressed();` +
`Mouse.isPressed(button);`

[float]
=== Parameters
When there is no value passed, it checks the status of the left mouse button.

`button`: which mouse button to check - `char`

* `MOUSE_LEFT (default)`

* `MOUSE_RIGHT`

* `MOUSE_MIDDLE`

[float]
=== Returns
`boolean` : reports wether a button is pressed or not.

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Example Code
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄


[source,arduino]
----
void setup(){
  //The switch that will initiate the Mouse press
  pinMode(2,INPUT);
  //The switch that will terminate the Mouse press
  pinMode(3,INPUT);
  //Start serial communication with the computer
  Serial1.begin(9600);
  //initiate the Mouse library
  Mouse.begin();
}

void loop(){
  //a variable for checking the button's state
  int mouseState=0;
  //if the switch attached to pin 2 is closed, press and hold the right mouse button and save the state ina  variable
  if(digitalRead(2) == HIGH){
    Mouse.press();
    mouseState=Mouse.isPressed();
  }
  //if the switch attached to pin 3 is closed, release the right mouse button and save the state in a variable
  if(digitalRead(3) == HIGH){
    Mouse.release();
    mouseState=Mouse.isPressed();
  }
  //print out the current mouse button state
  Serial1.println(mouseState);
  delay(10);
}
----
[%hardbreaks]

[float]
=== See also
// Link relevant content by category, such as other Reference terms (please add the tag #LANGUAGE#),
// definitions (please add the tag #DEFINITION#), and examples of Projects and Tutorials
// (please add the tag #EXAMPLE#)  ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄
[role="language"]
* #LANGUAGE# link:../mouseClick[Mouse.click] +
* #LANGUAGE# link:../mouseEnd[Mouse.end] +
* #LANGUAGE# link:../mouseMove[Mouse.move] +
* #LANGUAGE# link:../mousePress[Mouse.press] +
* #LANGUAGE# link:../mouseRelease[Mouse.release] +
* #LANGUAGE# link:../mouseIsPressed[Mouse.releaseAll]

--
// HOW TO USE SECTION ENDS
