---
title: "isWhitespace()"
categories: [ "Functions" ]
subCategories: [ "Characters" ]
---





= isWhitespace(thisChar)


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Description
Analyse if a char is a white space, that is space, formfeed ('\f'), newline ('\n'), carriage return ('\r'), horizontal tab ('\t'), and vertical tab ('\v')). 
Returns true if thisChar contains a white space. 
[%hardbreaks]


[float]
=== Syntax
[source,arduino]
`isWhitespace(thisChar)`


[float]
=== Parameters
`thisChar`: variable. *Allowed data types:* char

[float]
=== Returns
`true`: if thisChar is a white space.

--
// OVERVIEW SECTION ENDS



// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Example Code

[source,arduino]
----
if (isWhitespace(this))      // tests if this is a white space
{
	Serial.println("The character is a white space");
}
else
{
	Serial.println("The character is not a white space");
}

----

--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== See also

[role="language"]
* #LANGUAGE#  link:../../../variables/data-types/char[char]
* #LANGUAGE#  link:../../../structure/control-structure/if[if (conditional operators)]
* #LANGUAGE#  link:../../../structure/control-structure/while[while (conditional operators)]
* #LANGUAGE# link:../../communication/serial/read[read()]

--
// SEE ALSO SECTION ENDS
