---
title: "&"
title_expanded: reference operator
categories: [ "Structure" ]
subCategories: [ "Pointer Access Operators" ]
---





= & Reference Operator


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Description
Referencing is one of the features specifically for use with pointers. The ampersand operator `&` is used for this purpose. If `x` is a variable, then `&x` represents the address of the variable `x`.
[%hardbreaks]

--
// OVERVIEW SECTION ENDS



// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Example Code

[source,arduino]
----
int *p;       // declare a pointer to an int data type
int i = 5, result = 0;
p = &i;       // now 'p' contains the address of 'i'
result = *p;  // 'result' gets the value at the address pointed by 'p'
              // i.e., it gets the value of 'i' which is 5
----
[%hardbreaks]

[float]
=== Notes and Warnings
Pointers are one of the complicated subjects for beginners in learning C, and it is possible to write the vast majority of Arduino sketches without ever encountering pointers. However for manipulating certain data structures, the use of pointers can simplify the code, and knowledge of manipulating pointers is handy to have in one's toolkit.
[%hardbreaks]


--
// HOW TO USE SECTION ENDS




// SEE ALSO SECTION BEGINS
[#see_also]
--

[float]
=== See also

[role="language"]

[role="definition"]
* #DEFINITION#  https://en.wikipedia.org/wiki/Pointer_%28computer_programming%29[Pointers^]

--
// SEE ALSO SECTION ENDS
