---
title: SPI.setClockDivider()
---

= SPI.setClockDivider()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Description
This function should not be used in new projects. Use link:SPISettings[SPISettings]. with link:beginTransaction[SPI.beginTransaction()]. to configure SPI parameters.

Sets the SPI clock divider relative to the system clock. On AVR based boards, the dividers available are 2, 4, 8, 16, 32, 64 or 128. The default setting is SPI_CLOCK_DIV4, which sets the SPI clock to one-quarter the frequency of the system clock (4 Mhz for the boards at 16 MHz).

*For Arduino Due:* On the Due, the system clock can be divided by values from 1 to 255. The default value is 21, which sets the clock to 4 MHz like other Arduino boards.


[float]
=== Syntax
`SPI.setClockDivider(divider)`


[float]
=== Parameters

divider (only AVR boards):
* SPI_CLOCK_DIV2
* SPI_CLOCK_DIV4
* SPI_CLOCK_DIV8
* SPI_CLOCK_DIV16
* SPI_CLOCK_DIV32
* SPI_CLOCK_DIV64
* SPI_CLOCK_DIV128

chipSelectPin:	peripheral device CS pin (Arduino Due only)
divider:	a number from 1 to 255 (Arduino Due only)

[float]
=== Returns
None.

--
// OVERVIEW SECTION ENDS

