:source-highlighter: pygments
:pygments-style: arduino
:ext-relative: adoc


= Keyboard.println()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Description
Sends a keystroke to a connected computer, followed by a newline and carriage return.

`Keyboard.println()` must be called after initiating link:keyboardBegin{ext-relative}[Keyboard.begin()].
[%hardbreaks]


[float]
=== Syntax
`Keyboard.println()` +
`Keyboard.println(character)`+
`Keyboard.println(characters)`

[float]
=== Parameters
`character` : a char or int to be sent to the computer as a keystroke, followed by newline and carriage return.

`characters` : a string to be sent to the computer as a keystroke, followed by a newline and carriage return.

[float]
=== Returns
`int` : number of bytes sent

--
// OVERVIEW SECTION ENDS


// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Example Code
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄


[source,arduino]
----
void setup() {
  // make pin 2 an input and turn on the
  // pullup resistor so it goes high unless
  // connected to ground:
  pinMode(2, INPUT_PULLUP);
  Keyboard.begin();
}

void loop() {
  //if the button is pressed
  if(digitalRead(2)==LOW){
    //Send the message
    Keyboard.println("Hello!");
  }
}
----
[%hardbreaks]

[float]
=== Notes and Warnings
When you use the Keyboard.println() command, the Arduino takes over your keyboard! Make sure you have control before you use the command. A pushbutton to toggle the keyboard control state is effective.
[%hardbreaks]

[float]
=== See also
// Link relevant content by category, such as other Reference terms (please add the tag #LANGUAGE#),
// definitions (please add the tag #DEFINITION#), and examples of Projects and Tutorials
// (please add the tag #EXAMPLE#)  ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄

[role="language"]
* #LANGUAGE# link:keyboardEnd{ext-relative}[keyboard.end] +
* #LANGUAGE# link:keyboardPress{ext-relative}[keyboard.press] +
* #LANGUAGE# link:keyboardPrint{ext-relative}[keyboard.print] +
* #LANGUAGE# link:keyboardPrintln{ext-relative}[keyboard.println] +
* #LANGUAGE# link:keyboardRelease{ext-relative}[keyboard.release] +
* #LANGUAGE# link:keyboardReleaseAll{ext-relative}[keyboard.releaseAll] +
* #LANGUAGE# link:keyboardWrite{ext-relative}[keyboard.write]
--
// HOW TO USE SECTION ENDS
