---
title: Keyboard.release()
---
:source-highlighter: pygments
:pygments-style: arduino



= Keyboard.release()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Description
Lets go of the specified key. See link:../keyboardPress[Keyboard.press()] for more information.
[%hardbreaks]


[float]
=== Syntax
`Keyboard.release(key)`


[float]
=== Parameters
`key` : the key to release. `char`

[float]
=== Returns
`int` : the number of keys released

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Example Code
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄


[source,arduino]
----
// use this option for OSX:
char ctrlKey = KEY_LEFT_GUI;
// use this option for Windows and Linux:
//  char ctrlKey = KEY_LEFT_CTRL;

void setup() {
  // make pin 2 an input and turn on the
  // pullup resistor so it goes high unless
  // connected to ground:
  pinMode(2, INPUT_PULLUP);
  // initialize control over the keyboard:
  Keyboard.begin();
}

void loop() {
  while (digitalRead(2) == HIGH) {
    // do nothing until pin 2 goes low
    delay(500);
  }
  delay(1000);
  // new document:
  Keyboard.press(ctrlKey);
  Keyboard.press('n');
  delay(100);
  Keyboard.release(ctrlKey);
  Keyboard.release('n');
  // wait for new window to open:
  delay(1000);
}
----
[%hardbreaks]



[float]
=== See also
// Link relevant content by category, such as other Reference terms (please add the tag #LANGUAGE#),
// definitions (please add the tag #DEFINITION#), and examples of Projects and Tutorials
// (please add the tag #EXAMPLE#)  ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄

[role="language"]
* #LANGUAGE# link:../keyboardBegin[keyboard.begin]() +
* #LANGUAGE# link:../keyboardEnd[keyboard.end]() +
* #LANGUAGE# link:../keyboardPress[keyboard.press]() +
* #LANGUAGE# link:../keyboardPrint[keyboard.print]() +
* #LANGUAGE# link:../keyboardPrintln[keyboard.println]() +
* #LANGUAGE# link:../keyboardReleaseAll[keyboard.releaseAll]() +
* #LANGUAGE# link:../keyboardWrite[keyboard.write]()
--
// HOW TO USE SECTION ENDS
