:source-highlighter: pygments
:pygments-style: arduino



= Keyboard.print()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Description
Sends a keystroke to a connected computer.

`Keyboard.print()` must be called after initiating link:../keyboardBegin[Keyboard.begin()].
[%hardbreaks]


[float]
=== Syntax
`Keyboard.print(character)` +
`Keyboard.print(characters)`

[float]
=== Parameters
`character` : a char or int to be sent to the computer as a keystroke characters : a string to be sent to the computer as a keystroke.

[float]
=== Returns
`int` : number of bytes sent.

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Example Code
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄


[source,arduino]
----
void setup() {
  // make pin 2 an input and turn on the
  // pullup resistor so it goes high unless
  // connected to ground:
  pinMode(2, INPUT_PULLUP);
  Keyboard.begin();
}

void loop() {
  //if the button is pressed
  if(digitalRead(2)==LOW){
    //Send the message
    Keyboard.print("Hello!");
  }
}
----
[%hardbreaks]

[float]
=== Notes and Warnings
When you use the `Keyboard.print()` command, the Arduino takes over your keyboard! Make sure you have control before you use the command. A pushbutton to toggle the keyboard control state is effective.
[%hardbreaks]


[float]
=== See also
// Link relevant content by category, such as other Reference terms (please add the tag #LANGUAGE#),
// definitions (please add the tag #DEFINITION#), and examples of Projects and Tutorials
// (please add the tag #EXAMPLE#)  ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄

[role="language"]
* #LANGUAGE# link:../keyboardEnd[keyboard.end] +
* #LANGUAGE# link:../keyboardPress[keyboard.press] +
* #LANGUAGE# link:../keyboardPrint[keyboard.print] +
* #LANGUAGE# link:../keyboardPrintln[keyboard.println] +
* #LANGUAGE# link:../keyboardRelease[keyboard.release] +
* #LANGUAGE# link:../keyboardReleaseAll[keyboard.releaseAll] +
* #LANGUAGE# link:../keyboardWrite[keyboard.write]
--
// HOW TO USE SECTION ENDS
