:source-highlighter: pygments
:pygments-style: arduino
:ext-relative: adoc


= Keyboard.press()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Description
When called, `Keyboard.press()` functions as if a key were pressed and held on your keyboard. Useful when using link:keyboardModifier{ext-relative}[modifier keys]. To end the key press, use link:keyboardRelease{ext-relative}[Keyboard.release()] or link:keyboardReleaseAll{ext-relative}[Keyboard.releaseAll()].

It is necessary to call link:keyboardBegin{ext-relative}[Keyboard.begin()] before using `press()`.
[%hardbreaks]


[float]
=== Syntax
`Keyboard.press()`


[float]
=== Parameters
`char` : the key to press

[float]
=== Returns
Nothing

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Example Code
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄


[source,arduino]
----
// use this option for OSX:
char ctrlKey = KEY_LEFT_GUI;
// use this option for Windows and Linux:
//  char ctrlKey = KEY_LEFT_CTRL;

void setup() {
  // make pin 2 an input and turn on the
  // pullup resistor so it goes high unless
  // connected to ground:
  pinMode(2, INPUT_PULLUP);
  // initialize control over the keyboard:
  Keyboard.begin();
}

void loop() {
  while (digitalRead(2) == HIGH) {
    // do nothing until pin 2 goes low
    delay(500);
  }
  delay(1000);
  // new document:
  Keyboard.press(ctrlKey);
  Keyboard.press('n');
  delay(100);
  Keyboard.releaseAll();
  // wait for new window to open:
  delay(1000);
----
[%hardbreaks]



[float]
=== See also
// Link relevant content by category, such as other Reference terms (please add the tag #LANGUAGE#),
// definitions (please add the tag #DEFINITION#), and examples of Projects and Tutorials
// (please add the tag #EXAMPLE#)  ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄

[role="language"]
* #LANGUAGE# link:keyboardEnd{ext-relative}[keyboard.end] +
* #LANGUAGE# link:keyboardPress{ext-relative}[keyboard.press] +
* #LANGUAGE# link:keyboardPrint{ext-relative}[keyboard.print] +
* #LANGUAGE# link:keyboardPrintln{ext-relative}[keyboard.println] +
* #LANGUAGE# link:keyboardRelease{ext-relative}[keyboard.release] +
* #LANGUAGE# link:keyboardReleaseAll{ext-relative}[keyboard.releaseAll] +
* #LANGUAGE# link:keyboardWrite{ext-relative}[keyboard.write]
--
// HOW TO USE SECTION ENDS
