---
title: interrupts()
categories: [ "Functions" ]
subCategories: [ "Interrupts" ]
---





= interrupts()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Description
Re-enables interrupts (after they've been disabled by link:../nointerrupts[nointerrupts()]. Interrupts allow certain important tasks to happen in the background and are enabled by default. Some functions will not work while interrupts are disabled, and incoming communication may be ignored. Interrupts can slightly disrupt the timing of code, however, and may be disabled for particularly critical sections of code.
[%hardbreaks]


[float]
=== Syntax
`interrupts()`


[float]
=== Parameters
Nothing

[float]
=== Returns
Nothing

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Example Code
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄
The code enables Interrupts.

[source,arduino]
----
void setup() {}

void loop()
{
  noInterrupts();
  // critical, time-sensitive code here
  interrupts();
  // other code here
}
----

--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== See also

[role="language"]
* #LANGUAGE# link:../../external-interrupts/attachinterrupt[attachInterrupts()]
* #LANGUAGE# link:../../external-interrupts/detachinterrupt[detachInterrupts()]

--
// SEE ALSO SECTION ENDS
