---
title: noInterrupts()
categories: [ "Functions" ]
subCategories: [ "Interrupts" ]
---





= noInterrupts()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Description
Disables interrupts (you can re-enable them with link:../interrupts[`interrupts()`]). Interrupts allow certain important tasks to happen in the background and are enabled by default. Some functions will not work while interrupts are disabled, and incoming communication may be ignored. Interrupts can slightly disrupt the timing of code, however, and may be disabled for particularly critical sections of code.
[%hardbreaks]


[float]
=== Syntax
`noInterrupts()`


[float]
=== Parameters
None


[float]
=== Returns
Nothing

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Example Code
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄
The code shows how to enable interrupts.

[source,arduino]
----
void setup() {}

void loop() {
  noInterrupts();
  // critical, time-sensitive code here
  interrupts();
  // other code here
}
----
[%hardbreaks]


[float]
=== Notes and Warnings
Note that disabling interrupts on the Arduino Nano 3.3v BLE will make the board
not appear in the Ports tab, since this disables its ability to respond to USB
handshakes (see  https://arduino.stackexchange.com/a/90045/83235[this answer^])

--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== See also

--
// SEE ALSO SECTION ENDS
