---
title: Parent of Entity Title
categories: [ "Functions" ] 
subCategories: [ "Subcategory Name" ]
---
// ARDUINO LANGUAGE REFERENCE TAG (above)   ►►►►► ALWAYS INCLUDE IN YOUR FILE ◄◄◄◄◄
// title will show up in the Index of all Reference terms
// categories: Pick between Structure, Variable or Function
// The subcategory within the ones available in the index ("Digital I/O", "Arithmetic Operators")

// ARDUINO PYGMENTS HIGHLIGHT ATTRIBUTE   ►►►►► ALWAYS INCLUDE IN YOUR FILE ◄◄◄◄◄
:source-highlighter: pygments
:pygments-style: arduino


// PAGE TITLE   ►►►►► THIS IS MANDATORY ◄◄◄◄◄
= Parent of Entities title()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Description
// Describe what this group of Reference terms is used for, -- THIS SECTION IS MANDATORY --
Used for communication between the Arduino board and a computer or other devices. All Arduino boards have at least one serial port (also known as a UART or USART): Serial. It communicates on digital pins 0 (RX) and 1 (TX) as well as with the computer via USB. Thus, if you use these functions, you cannot also use pins 0 and 1 for digital input or output. +
You can use the Arduino environment's built-in serial monitor to communicate with an Arduino board. Click the serial monitor button in the toolbar and select the same baud rate used in the call to `begin()`.
[%hardbreaks]
The *Arduino Mega* has three additional serial ports: `Serial1` on pins 19 (RX) and 18 (TX), `Serial2` on pins 17 (RX) and 16 (TX), `Serial3` on pins 15 (RX) and 14 (TX). To use these pins to communicate with your personal computer, you will need an additional USB-to-serial adaptor, as they are not connected to the Mega's USB-to-serial adaptor. To use them to communicate with an external TTL serial device, connect the TX pin to your device's RX pin, the RX to your device's TX pin, and the ground of your Mega to your device's ground. (Don't connect these pins directly to an RS232 serial port; they operate at +/- 12V and can damage your Arduino board.)
[%hardbreaks]
The *Arduino DUE* has three additional 3.3V TTL serial ports: `Serial1` on pins 19 (RX) and 18 (TX); `Serial2` on pins 17 (RX) and 16 (TX), `Serial3` on pins 15 (RX) and 14 (TX). Pins 0 and 1 are also connected to the corresponding pins of the ATmega16U2 USB-to-TTL Serial chip, which is connected to the USB debug port. Additionally, there is a native USB-serial port on the SAM3X chip, SerialUSB'.
[%hardbreaks]
The *Arduino Leonardo* board uses `Serial1` to communicate via TTL (5V) serial on pins 0 (RX) and 1 (TX). `Serial` is reserved for USB CDC communication. For more information, refer to the Leonardo getting started page and hardware page.

--
// OVERVIEW SECTION ENDS




// FUNCTIONS SECTION STARTS
[#functions]
--

'''

[float]
=== Functions
// List all the functions within this Reference parent, ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄
http://arduino.cc[if] (Serial) +
http://arduino.cc[available()] +
http://arduino.cc[begin()] +
http://arduino.cc[end()] +
http://arduino.cc[find()] +
http://arduino.cc[findUntil()] +
http://arduino.cc[flush()] +
http://arduino.cc[parseFloat()] +
http://arduino.cc[parseInt()] +
http://arduino.cc[peek()] +
http://arduino.cc[print()] +
http://arduino.cc[println()] +
http://arduino.cc[read()] +
http://arduino.cc[readBytes()] +
http://arduino.cc[readBytesUntil()] +
http://arduino.cc[setTimeout()] +
http://arduino.cc[write()] +
http://arduino.cc[serialEvent()]

'''

--
// FUNCTIONS SECTION ENDS


// SEE ALSO SECTION STARTS
[#seealso]
--

[float]
=== See also
// Link relevant content by category, such as other Reference terms (please add the tag #LANGUAGE#), 
// definitions (please add the tag #DEFINITION#), and examples of Projects and Tutorials
// (please add the tag #EXAMPLE#)  ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄


[role="language"]
// Whenever you want to link to another Reference term, or more in general to a relative link,
// use the syntax shown below. Please note that the file format is subsituted by  attribute.
// Please note that you always need to replace spaces that you might find in folder/file names with %20
* #LANGUAGE# link:../AsciiDoc_Template-Single_Entity[Single Entity]
* #LANGUAGE# link:../../AsciiDoc_Dictionary/AsciiDoc_Template-Dictionary[AsciiDoc Template Dictionary]

[role="definition"]
// Please note that all external links need to be opened in a new window/tab by adding ^ right before the last square brackets
* #DEFINITION# http://arduino.cc/en/Tutorial/PWM[PWM^]

[role="example"]
// Please note that all external links need to be opened in a new window/tab by adding ^ right before the last square brackets
* #EXAMPLE# http://arduino.cc/en/Tutorial/Blink[Blink^]

--
// SEE ALSO SECTION ENDS
