---
title: randomSeed()
categories: [ "Functions" ]
subCategories: [ "Random Numbers" ]
---





= randomSeed(seed)


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Description
`randomSeed()` initializes the pseudo-random number generator, causing it to start at an arbitrary point in its random sequence. This sequence, while very long, and random, is always the same.

If it is important for a sequence of values generated by `random()` to differ, on subsequent executions of a sketch, use randomSeed() to initialize the random number generator with a fairly random input, such as `analogRead()` on an unconnected pin.

Conversely, it can occasionally be useful to use pseudo-random sequences that repeat exactly. This can be accomplished by calling `randomSeed()` with a fixed number, before starting the random sequence.
[%hardbreaks]


[float]
=== Syntax
`randomSeed(seed)`


[float]
=== Parameters
`seed`: non-zero number to initialize the pseudo-random sequence. Allowed data types: `unsigned long`.


[float]
=== Returns
Nothing

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Example Code
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄
The code generates a pseudo-random number and sends the generated number to the serial port.

[source,arduino]
----
long randNumber;

void setup() {
  Serial.begin(9600);
  randomSeed(analogRead(0));
}

void loop() {
  randNumber = random(300);
  Serial.println(randNumber);
  delay(50);
}
----
[%hardbreaks]

[float]
=== Notes and Warnings
If the `seed` is 0, `randomSeed(seed)` will have no effect.

--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== See also

--
// SEE ALSO SECTION ENDS
