---
title: Keyboard.println()
---




= Keyboard.println()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Description
Sends a keystroke to a connected computer, followed by a newline and carriage return.

`Keyboard.println()` must be called after initiating link:../keyboardbegin[Keyboard.begin()].
[%hardbreaks]


[float]
=== Syntax
`Keyboard.println()` +
`Keyboard.println(character)`+
`Keyboard.println(characters)`

[float]
=== Parameters
`character` : a char or int to be sent to the computer as a keystroke, followed by newline and carriage return.

`characters` : a string to be sent to the computer as a keystroke, followed by a newline and carriage return.

[float]
=== Returns
`size_t` : number of bytes sent

--
// OVERVIEW SECTION ENDS


// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Example Code
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄


[source,arduino]
----
#include <Keyboard.h>

void setup() {
  // make pin 2 an input and turn on the
  // pullup resistor so it goes high unless
  // connected to ground:
  pinMode(2, INPUT_PULLUP);
  Keyboard.begin();
}

void loop() {
  //if the button is pressed
  if(digitalRead(2)==LOW){
    //Send the message
    Keyboard.println("Hello!");
  }
}
----
[%hardbreaks]

[float]
=== Notes and Warnings
When you use the Keyboard.println() command, the Arduino takes over your keyboard! Make sure you have control before you use the command. A pushbutton to toggle the keyboard control state is effective.

--
// HOW TO USE SECTION ENDS
