---
title: Keyboard.press()
---




= Keyboard.press()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Description
When called, `Keyboard.press()` functions as if a key were pressed and held on your keyboard. Useful when using link:../keyboard/keyboardmodifiers[modifier keys]. To end the key press, use link:../keyboard/keyboardrelease[Keyboard.release()] or link:../keyboard/keyboardreleaseall[Keyboard.releaseAll()].

It is necessary to call link:../keyboard/keyboardbegin[Keyboard.begin()] before using `press()`.
[%hardbreaks]


[float]
=== Syntax
`Keyboard.press(key)`


[float]
=== Parameters
`key`: the key to press. Allowed data types: `char`.


[float]
=== Returns
Number of key presses sent. Data type: `size_t`.

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Example Code
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄


[source,arduino]
----
#include <Keyboard.h>

// use this option for OSX:
char ctrlKey = KEY_LEFT_GUI;
// use this option for Windows and Linux:
//  char ctrlKey = KEY_LEFT_CTRL;

void setup() {
  // make pin 2 an input and turn on the
  // pullup resistor so it goes high unless
  // connected to ground:
  pinMode(2, INPUT_PULLUP);
  // initialize control over the keyboard:
  Keyboard.begin();
}

void loop() {
  while (digitalRead(2) == HIGH) {
    // do nothing until pin 2 goes low
    delay(500);
  }
  delay(1000);
  // new document:
  Keyboard.press(ctrlKey);
  Keyboard.press('n');
  delay(100);
  Keyboard.releaseAll();
  // wait for new window to open:
  delay(1000);
}
----

--
// HOW TO USE SECTION ENDS
