---
title: detachInterrupt()
categories: [ "Functions" ]
subCategories: [ "External Interrupts" ]
---





= detachInterrupt()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Description
Turns off the given interrupt.
[%hardbreaks]


[float]
=== Syntax
`detachInterrupt(digitalPinToInterrupt(pin))` (recommended) +
`detachInterrupt(interrupt)` (not recommended) +
`detachInterrupt(pin)` (Not recommended. Additionally, this syntax only works on Arduino SAMD Boards, Uno WiFi Rev2, Due, and 101.)


[float]
=== Parameters
`interrupt`: the number of the interrupt to disable (see link:../attachinterrupt[attachInterrupt()] for more details). +
`pin`: the Arduino pin number of the interrupt to disable


[float]
=== Returns
Nothing

--
// OVERVIEW SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== See also
[role="language"]
* #LANGUAGE# link:../../external-interrupts/attachinterrupt[attachInterrupt()]
* #LANGUAGE# link:../../interrupts/interrupts[interrupts()]
* #LANGUAGE# link:../../interrupts/nointerrupts[noInterrupts()]
--
// SEE ALSO SECTION ENDS
