---
title: ">="
title_expanded: greater than or equal to
categories: [ "Structure" ]
subCategories: [ "Comparison Operators" ]
---





= >= Greater Than or Equal To


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Description
Compares the variable on the left with the value or variable on the right of the operator. Returns true when the operand on the left is greater (bigger) than or equal to the operand on the right. Please note that you may compare variables of different data types, but that could generate unpredictable results, it is therefore recommended to compare variables of the same data type including the signed/unsigned type.
[%hardbreaks]


[float]
=== Syntax
[source,arduino]
----
x >= y;   // is true if x is bigger than or equal to y and it is false if x is smaller than y
----

[float]
=== Parameters
`x`: variable. *Allowed data types:* int, float, double, byte, short, long +
`y`: variable or constant. *Allowed data types:* int, float, double, byte, short, long

--
// OVERVIEW SECTION ENDS



// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Example Code

[source,arduino]
----
if (x>=y)      // tests if x is greater (bigger) than or equal to y
{
// do something only if the comparison result is true
}
----
[%hardbreaks]

[float]
=== Notes and Warnings
Positive numbers are greater than negative numbers. 
[%hardbreaks]

--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== See also


--
// SEE ALSO SECTION ENDS
