---
title: millis()
categories: [ "Functions" ]
subCategories: [ "Time" ]
---

= millis()

// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Description
Returns the number of milliseconds passed since the Arduino board began running the current program. This number will overflow (go back to zero), after approximately 50 days.
[%hardbreaks]


[float]
=== Syntax
`time = millis()`


[float]
=== Parameters
None


[float]
=== Returns
Number of milliseconds passed since the program started. Data type: `unsigned long`.

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Example Code
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄
This example code prints on the serial port the number of milliseconds passed since the Arduino board started running the code itself.

[source,arduino]
----
unsigned long myTime;

void setup() {
  Serial.begin(9600);
}
void loop() {
  Serial.print("Time: ");
  myTime = millis();

  Serial.println(myTime); //prints time since program started
  delay(1000);          // wait a second so as not to send massive amounts of data
}
----
This example provides a better idea how millis() can actually be used to generate periodic code that doesn't interfere with concurrent code, running at the MCU execution rate.
[source,arduino]
----
/**
 * Example code demonstrating a way to use the millis() function to generate a periodic 
 * event that avoids the execution blocking pitfall of the Delay_ms() function.  This 
 * deomnstration involves a periodic message sent to a Serial Terminal, along with a 
 * concurrent blinking of the built-in LED at around 6Hz [on an UNO].  
 * 
 * To experience the full extent of this example code, open a Serial Monitor so you can
 * both see the periodic message, timed using the millis() function, while also 
 * witnessing the concurrent blink of the built-in LED.
 * 
 * Also, the TX LED will flash once per period while the neighboing Built-in LED rapidly
 * flashes, providing yet another visual.
 */

const int PERIOD = 1000;                             // In milliseconds - e.g. 1000 = 1 second

unsigned long next_millis;
int periods                               = 0;
String message                            = "";
#define MSG_FRAG  " Periods so far."

const int LED_BLINK_PERIOD_AS_LOP_CYCLES  = 29200;   // Produces a ~6HZ blink on an UNO
int led_blink_loop_count                  = 0;
 
void setup() {
    pinMode(LED_BUILTIN, OUTPUT);  // Prepare to blink the built-in LED
    Serial.begin(115200);          // Make sure to set the serial montior to 115200 BAUD
    
    Serial.println("Demonstration of the use of millis() in place of Delay_ms()");

    next_millis = millis() + PERIOD;
    message = "1 Period so far.";  // Manages the singular vs plural dilemma
}
 
void loop() {
    // This, and the next line, are what take the place of the Delay_ms() call.
    if(millis() >= next_millis){
        next_millis = millis() + PERIOD;

        // Replace the following example code with the code you want executed periodically:
        message = ++periods;
        message += MSG_FRAG;
        Serial.println(message);  // Sends a periodic message to the serial monitor.
    }
   
    //Replace the following example code with the code you want to run concurrently:
    if (++led_blink_loop_count >= LED_BLINK_PERIOD_AS_LOP_CYCLES)
    {
        led_blink_loop_count = 0;
        digitalWrite(LED_BUILTIN, digitalRead(LED_BUILTIN) ^ 1);  // Toggle the LED state
    }
}
----
[%hardbreaks]

[float]
=== Notes and Warnings
Please note that the return value for millis() is of type `unsigned long`, logic errors may occur if a programmer tries to do arithmetic with smaller data types such as `int`. Even signed `long` may encounter errors as its maximum value is half that of its unsigned counterpart.

--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== See also

[role="example"]
* #EXAMPLE# http://arduino.cc/en/Tutorial/BlinkWithoutDelay[Blink Without Delay^]

--
// SEE ALSO SECTION ENDS
