---
title: Stream.readBytesUntil()
---




= readBytesUntil()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Description
`readBytesUntil()` reads characters from a stream into a buffer. The function terminates if the terminator character is detected, the determined length has been read, or it times out (see link:../streamsettimeout[setTimeout()]). The function returns the characters up to the last character before the supplied terminator. The terminator itself is not returned in the buffer.

`readBytesUntil()` returns the number of bytes placed in the buffer. A 0 means no valid data was found.

This function is part of the Stream class, and is called by any class that inherits from it (Wire, Serial, etc). See the link:../../stream[Stream class] main page for more information.
[%hardbreaks]


[float]
=== Syntax
`stream.readBytesUntil(character, buffer, length)`


[float]
=== Parameters
`stream` : an instance of a class that inherits from Stream.

`character` : the character to search for (`char`)

`buffer`: the buffer to store the bytes in (`char[]` or `byte[]`)

`length` : the number of bytes to `read(int)`

[float]
=== Returns
The number of bytes placed in the buffer.

--
// OVERVIEW SECTION ENDS


// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Notes and Warnings
The terminator character is discarded from the stream.
[%hardbreaks]

--
// HOW TO USE SECTION ENDS
