---
title: Stream.readStringUntil()
---




= readStringUntil()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Description
`readStringUntil()` reads characters from a stream into a String. The function terminates if the terminator character is detected or it times out (see link:../streamsettimeout[setTimeout()]).

This function is part of the Stream class, and can be called by any class that inherits from it (Wire, Serial, etc). See the link:../../stream[Stream class] main page for more information.
[%hardbreaks]


[float]
=== Syntax
`stream.readString(terminator)`


[float]
=== Parameters
`stream`: an instance of a class that inherits from Stream. +
`terminator`: the character to search for. Allowed data types: `char`.


[float]
=== Returns
The entire String read from a stream, up to the terminator character

--
// OVERVIEW SECTION ENDS


// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Notes and Warnings
The terminator character is discarded from the stream.
[%hardbreaks]

--
// HOW TO USE SECTION ENDS
