---
title: Stream.readStringUntil()
---
:source-highlighter: pygments
:pygments-style: arduino



= readStringUntil()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Description
`readStringUntil()` reads characters from a stream into a string. The function terminates if the terminator character is detected or it times out (see link:../streamSetTimeout[setTimeout()]).

This function is part of the Stream class, and is called by any class that inherits from it (Wire, Serial, etc). See the link:../../stream[Stream class] main page for more information.
[%hardbreaks]


[float]
=== Syntax
`stream.readString(terminator)`


[float]
=== Parameters
`terminator` : the character to search for (`char`)

[float]
=== Returns
The entire string read from a stream, until the terminator character is detected.

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Example Code
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄

[float]
=== See also
// Link relevant content by category, such as other Reference terms (please add the tag #LANGUAGE#),
// definitions (please add the tag #DEFINITION#), and examples of Projects and Tutorials
// (please add the tag #EXAMPLE#)  ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄
[role="language"]
* #LANGUAGE# link:../../stream[stream]
--
// HOW TO USE SECTION ENDS
