---
title: "~"
title_expanded: bitwise not
categories: [ "Structure" ]
subCategories: [ "Bitwise Operators" ]
---





= ~ Bitwise NOT


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Description
The bitwise NOT operator in C++ is the tilde character `~`. Unlike & and |, the bitwise NOT operator is applied to a single operand to its right. Bitwise NOT changes each bit to its opposite: 0 becomes 1, and 1 becomes 0.
[%hardbreaks]

In other words:

    0  1    operand1
    -----
    1  0   ~operand1
[%hardbreaks]
--
// OVERVIEW SECTION ENDS



// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Example Code

[source,arduino]
----
int a = 103;    // binary:  0000000001100111
int b = ~a;     // binary:  1111111110011000 = -104
----
[%hardbreaks]

[float]
=== Notes and Warnings
You might be surprised to see a negative number like -104 as the result of this operation. This is because the highest bit in an int variable is the so-called sign bit. If the highest bit is 1, the number is interpreted as negative. This encoding of positive and negative numbers is referred to as two's complement. For more information, see the Wikipedia article on http://en.wikipedia.org/wiki/Twos_complement[two's complement^].

As an aside, it is interesting to note that for any integer x, ~x is the same as -x-1.

At times, the sign bit in a signed integer expression can cause some unwanted surprises.
[%hardbreaks]

--
// HOW TO USE SECTION ENDS



// SEE ALSO BEGINS
[#see_also]
--

[float]
=== See also

[role="language"]

[role="example"]
* #EXAMPLE# https://www.arduino.cc/playground/Code/BitMath[BitMath Tutorial^]

--
//SEE ALSO SECTION ENDS
