---
title: "+"
title_expanded: "addition"
categories: [ "Structure" ]
subCategories: [ "Arithmetic Operators" ]
---





= + Addition


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Description
*Addition* is one of the four primary arithmetic operations. The operator `+` (plus) operates on two operands to produce the sum.
[%hardbreaks]


[float]
=== Syntax
[source,arduino]
----
sum = operand1 + operand2;
----

[float]
=== Parameters
`sum` : variable. *Allowed data types:* int, float, double, byte, short, long +
`operand1` : variable or constant. *Allowed data types:* int, float, double, byte, short, long +
`operand2` : variable or constant. *Allowed data types:* int, float, double, byte, short, long
[%hardbreaks]
--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Example Code

[source,arduino]
----
int a = 5, b = 10, c = 0;
c = a + b; // the variable 'c' gets a value of 15 after this statement is executed
----
[%hardbreaks]

[float]
=== Notes and Warnings
1. The addition operation can overflow if the result is larger than that which can be stored in the data type (e.g. adding 1 to an integer with the value 32,767 gives -32,768).

2. If one of the numbers (operands) are of the type float or of type double, floating point math will be used for the calculation.

3. If the operands are of float / double data type and the variable that stores the sum is an integer, then only the integral part is stored and the fractional part of the number is lost.

[source,arduino]
----
float a = 5.5, b = 6.6;
int c = 0;
c = a + b; // the variable 'c' stores a value of 12 only as opposed to the expected sum of 12.1
----
[%hardbreaks]
--
// HOW TO USE SECTION ENDS




// SEE ALSO SECTION
[#see_also]
--

[float]
=== See also

[role="language"]

--
// SEE ALSO SECTION ENDS
