---
title: "="
title_expanded: "assignment operator"
categories: [ "Structure" ]
subCategories: [ "Arithmetic Operators" ]
---





= = Assignment (single equal sign)


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Description
The single equal sign `=` in the C programming language is called the assignment operator. It has a different meaning than in algebra class where it indicated an equation or equality. The assignment operator tells the microcontroller to evaluate whatever value or expression is on the right side of the equal sign, and store it in the variable to the left of the equal sign.
[%hardbreaks]

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Example Code



[source,arduino]
----
int sensVal;              // declare an integer variable named sensVal
sensVal = analogRead(0);  // store the (digitized) input voltage at analog pin 0 in SensVal
----
[%hardbreaks]

[float]
=== Notes and Warnings
1. The variable on the left side of the assignment operator ( = sign ) needs to be able to hold the value stored in it. If it is not large enough to hold a value, the value stored in the variable will be incorrect.

2. Don't confuse the assignment operator [ = ] (single equal sign) with the comparison operator [ == ] (double equal signs), which evaluates whether two expressions are equal.
[%hardbreaks]

--
// HOW TO USE SECTION ENDS

// SEE ALSO SECTION STARTS
[#see_also]
--

[float]
=== See also

[role="language"]
* #LANGUAGE#  link:../../control-structure/if[if (conditional operators)]
* #LANGUAGE#  link:../../../variables/data-types/char[char]
* #LANGUAGE#  link:../../../variables/data-types/int[int]
* #LANGUAGE#  link:../../../variables/data-types/long[long]

--
// SEE ALSO SECTION ENDS
