---
title: SPI
categories: [ "Functions" ]
subCategories: [ "Communication" ]
---


= SPI


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Description


This library allows you to communicate with SPI devices, with the Arduino as the controller device. This library is bundled with every Arduino platform (avr, megaavr, mbed, samd, sam, arc32), so *you do not need to install* the library separately.

To use this library

`#include <SPI.h>`

To read more about Arduino and SPI, you can visit the https://docs.arduino.cc/learn/communication/spi[Arduino & Serial Peripheral Interface (SPI)] guide.

--
// OVERVIEW SECTION ENDS


// FUNCTIONS SECTION STARTS
[#functions]
--

'''

[float]
=== Functions
link:../spi/spisettings[SPISettings] +
link:../spi/begin[begin()] +
link:../spi/begintransaction[beginTransaction()] +
link:../spi/endtransaction[endTransaction()] +
link:../spi/end[end()] +
link:../spi/setbitorder[setBitOrder()] +
link:../spi/setclockdivider[setClockDivider()] +
link:../spi/setdatamode[setDataMode()] +
link:../spi/transfer[transfer()] +
link:../spi/usinginterrupt[usingInterrupt()]

'''

--
// SEEALSO SECTION ENDS
