:source-highlighter: pygments
:pygments-style: arduino
:ext-relative: adoc


= available()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Description
Get the number of bytes (characters) available for reading from the serial port. This is data that's already arrived and stored in the serial receive buffer (which holds 64 bytes). `available()` inherits from the Stream utility class.
[%hardbreaks]


[float]
=== Syntax
`Serial.available()`

_Arduino Mega only:_

`Serial1.available()` +
`Serial2.available()` +
`Serial3.available()`


[float]
=== Parameters
Nothing

[float]
=== Returns
The number of bytes available to read .
--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[source,arduino]
----
int incomingByte = 0;	// for incoming serial data

void setup() {
	Serial.begin(9600);	// opens serial port, sets data rate to 9600 bps
}

void loop() {

	// send data only when you receive data:
	if (Serial.available() > 0) {
		// read the incoming byte:
		incomingByte = Serial.read();

		// say what you got:
		Serial.print("I received: ");
		Serial.println(incomingByte, DEC);
	}
}
----
[%hardbreaks]

*Arduino Mega example:*
[source,arduino]
----
void setup() {
  Serial.begin(9600);
  Serial1.begin(9600);

}

void loop() {
  // read from port 0, send to port 1:
  if (Serial.available()) {
    int inByte = Serial.read();
    Serial1.print(inByte, BYTE);

  }
  // read from port 1, send to port 0:
  if (Serial1.available()) {
    int inByte = Serial1.read();
    Serial.print(inByte, BYTE);
  }
}
----

[float]
=== See also
// Link relevant content by category, such as other Reference terms (please add the tag #LANGUAGE#),
// definitions (please add the tag #DEFINITION#), and examples of Projects and Tutorials
// (please add the tag #EXAMPLE#)  ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄
[role="language"]
* #LANGUAGE# link:begin{ext-relative}[begin()] +
* #LANGUAGE# link:end{ext-relative}[end()] +
* #LANGUAGE# link:available{ext-relative}[available()] +
* #LANGUAGE# link:read{ext-relative}[read()] +
* #LANGUAGE# link:peek{ext-relative}[peek()] +
* #LANGUAGE# link:flush{ext-relative}[flush()] +
* #LANGUAGE# link:print{ext-relative}[print()] +
* #LANGUAGE# link:println{ext-relative}[println()] +
* #LANGUAGE# link:write{ext-relative}[write()] +
* #LANGUAGE# link:serialEvent{ext-relative}[SerialEvent()] +
* #LANGUAGE# link:serialAvailable{ext-relative}[(Serial.available)]

--
// HOW TO USE SECTION ENDS
