---
title: Serial.parseFloat()
---




= Serial.parseFloat()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Description
`Serial.parseFloat()` returns the first valid floating point number from the Serial buffer. Characters that are not digits (or the minus sign) are skipped. `parseFloat()` is terminated by the first character that is not a floating point number. The function terminates if it times out (see link:../settimeout[Serial.setTimeout()]).

`Serial.parseFloat()` inherits from the link:../../stream[Stream] utility class.
[%hardbreaks]


[float]
=== Syntax
`_Serial_.parseFloat()`


[float]
=== Parameters
`_Serial_`: serial port object. See the list of available serial ports for each board on the link:../../serial[Serial main page].

[float]
=== Returns
`float`

--
// OVERVIEW SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== See also

[role="language"]
* #LANGUAGE# link:../../stream[stream()]
* #LANGUAGE# link:../../stream/streamparsefloat[Stream.parseFloat()]

--
// SEE ALSO SECTION ENDS
