---
title: Serial.parseInt()
---




= parseInt()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Description
Looks for the next valid integer in the incoming serial. The function terminates if it times out (see link:../settimeout[Serial.setTimeout()]).

`Serial.parseInt()` inherits from the link:../../stream[Stream] utility class.


In particular:

* Parsing stops when no characters have been read for a configurable time-out value, or a non-digit is read; +
* If no valid digits were read when the time-out (see Serial.setTimeout()) occurs, 0 is returned;
[%hardbreaks]


[float]
=== Syntax
`_Serial_.parseInt()` +
`_Serial_.parseInt(lookahead)` +
`_Serial_.parseInt(lookahead, ignore)`


[float]
=== Parameters
`_Serial_`: serial port object. See the list of available serial ports for each board on the link:https://www.arduino.cc/en/Reference/serial[Serial main page]. +
`lookahead`: the mode used to look ahead in the stream for an integer. Allowed data types: `LookaheadMode`. Allowed `lookahead` values:

* `SKIP_ALL`: all characters other than digits or a minus sign are ignored when scanning the stream for an integer. This is the default mode.
* `SKIP_NONE`: Nothing is skipped, and the stream is not touched unless the first waiting character is valid.
* `SKIP_WHITESPACE`: Only tabs, spaces, line feeds, and carriage returns are skipped.

`ignore`: used to skip the indicated char in the search. Used for example to skip thousands divider. Allowed data types: `char`


[float]
=== Returns
The next valid integer. Data type: `long`.

--
// OVERVIEW SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== See also

[role="language"]
* #LANGUAGE# link:../begin[begin()] +
* #LANGUAGE# link:../end[end()] +
* #LANGUAGE# link:../available[available()] +
* #LANGUAGE# link:../read[read()] +
* #LANGUAGE# link:../peek[peek()] +
* #LANGUAGE# link:../flush[flush()] +
* #LANGUAGE# link:../print[print()] +
* #LANGUAGE# link:../println[println()] +
* #LANGUAGE# link:../write[write()] +
* #LANGUAGE# link:../serialevent[SerialEvent()] +
* #LANGUAGE# link:../../stream/streamparsefloat[Stream.parseFloat()]

--
// SEE ALSO SECTION ENDS
