:source-highlighter: pygments
:pygments-style: arduino
:ext-relative: adoc


= println()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Description
Prints data to the serial port as human-readable ASCII text followed by a carriage return character (ASCII 13, or '\r') and a newline character (ASCII 10, or '\n'). This command takes the same forms as link:print{ext-relative}[Serial.print().
[%hardbreaks]


[float]
=== Syntax
`Serial.println(val)` +
`Serial.println(val, format)`


[float]
=== Parameters
`val`: the value to print - any data type

`format`: specifies the number base (for integral data types) or number of decimal places (for floating point types)

[float]
=== Returns
`size_t` (`long`): `println()` returns the number of bytes written, though reading that number is optional
--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Example Code
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄


[source,arduino]
----
/*
 Analog input reads an analog input on analog in 0, prints the value out.
 created 24 March 2006
 by Tom Igoe
 */

int analogValue = 0;    // variable to hold the analog value

void setup() {
  // open the serial port at 9600 bps:
  Serial.begin(9600);
}

void loop() {
  // read the analog input on pin 0:
  analogValue = analogRead(0);

  // print it out in many formats:
  Serial.println(analogValue);       // print as an ASCII-encoded decimal
  Serial.println(analogValue, DEC);  // print as an ASCII-encoded decimal
  Serial.println(analogValue, HEX);  // print as an ASCII-encoded hexadecimal
  Serial.println(analogValue, OCT);  // print as an ASCII-encoded octal
  Serial.println(analogValue, BIN);  // print as an ASCII-encoded binary

  // delay 10 milliseconds before the next reading:
  delay(10);
----
[%hardbreaks]

[float]
=== See also
// Link relevant content by category, such as other Reference terms (please add the tag #LANGUAGE#),
// definitions (please add the tag #DEFINITION#), and examples of Projects and Tutorials
// (please add the tag #EXAMPLE#)  ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄
[role="language"]
* #LANGUAGE# link:begin{ext-relative}[begin()] +
* #LANGUAGE# link:end{ext-relative}[end()] +
* #LANGUAGE# link:available{ext-relative}[available()] +
* #LANGUAGE# link:read{ext-relative}[read()] +
* #LANGUAGE# link:peek{ext-relative}[peek()] +
* #LANGUAGE# link:flush{ext-relative}[flush()] +
* #LANGUAGE# link:print{ext-relative}[print()] +
* #LANGUAGE# link:println{ext-relative}[println()] +
* #LANGUAGE# link:write{ext-relative}[write()] +
* #LANGUAGE# link:serialEvent{ext-relative}[SerialEvent()]
--
// HOW TO USE SECTION ENDS
