:source-highlighter: pygments
:pygments-style: arduino



= Serial.readBytes()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Description
`Serial.readBytes()` reads characters from the serial port into a buffer. The function terminates if the determined length has been read, or it times out (see link:../setTimeout[Serial.setTimeout()]).

`Serial.readBytes()` returns the number of characters placed in the buffer. A 0 means no valid data was found.

`Serial.readBytes()` inherits from the link:../stream[Stream] utility class.
[%hardbreaks]


[float]
=== Syntax
`Serial.readBytes(buffer, length)`


[float]
=== Parameters
`buffer`: the buffer to store the bytes in (`char[]` or `byte[]`)

`length` : the number of bytes to read (`int`)

[float]
=== Returns
`byte`

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--


[float]
=== See also
// Link relevant content by category, such as other Reference terms (please add the tag #LANGUAGE#),
// definitions (please add the tag #DEFINITION#), and examples of Projects and Tutorials
// (please add the tag #EXAMPLE#)  ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄
[role="language"]
* #LANGUAGE# link:../../stream[stream] +
* #LANGUAGE# link:../../stream/streamReadBytes[stream.readBytes()]

--
// HOW TO USE SECTION ENDS
