---
title: Serial.readBytes()
---




= Serial.readBytes()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Description
`Serial.readBytes()` reads characters from the serial port into a buffer. The function terminates if the determined length has been read, or it times out (see link:../settimeout[Serial.setTimeout()]).

`Serial.readBytes()` returns the number of characters placed in the buffer. A 0 means no valid data was found.

`Serial.readBytes()` inherits from the link:../../stream[Stream] utility class.
[%hardbreaks]


[float]
=== Syntax
`Serial.readBytes(buffer, length)`


[float]
=== Parameters
`buffer`: the buffer to store the bytes in (`char[]` or `byte[]`)

`length` : the number of bytes to read (`int`)

[float]
=== Returns
The number of bytes placed in the buffer (`size_t`)

--
// OVERVIEW SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== See also

[role="language"]
* #LANGUAGE# link:../../stream[stream]
* #LANGUAGE# link:../../stream/streamreadbytes[stream.readBytes()]

--
// SEE ALSO SECTION ENDS
