---
title: Serial.readBytesUntil()
---




= Serial.readBytesUntil()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Description
Serial.readBytesUntil() reads characters from the serial buffer into an array. The function terminates if the terminator character is detected, the determined length has been read, or it times out (see link:../settimeout[Serial.setTimeout()]). The function returns the characters up to the last character before the supplied terminator. The terminator itself is not returned in the buffer.

`Serial.readBytesUntil()` returns the number of characters read into the buffer. A 0 means no valid data was found.

`Serial.readBytesUntil()` inherits from the link:../../stream[Stream] utility class.
[%hardbreaks]


[float]
=== Syntax
`Serial.readBytesUntil(character, buffer, length)`


[float]
=== Parameters
`character` : the character to search for (`char`)

`buffer`: the buffer to store the bytes in (`char[]` or `byte[]`)

`length` : the number of bytes to read (`int`)

[float]
=== Returns
`size_t`

--
// OVERVIEW SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== See also

[role="language"]
* #LANGUAGE# link:../../stream[Stream]
* #LANGUAGE# link:../../stream/streamreadbytesuntil[Stream.readByteUntil()]

--
// SEE ALSO SECTION ENDS
