---
title: Serial.readStringUntil()
---




= readStringUntil()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Description
`readStringUntil()` reads characters from the serial buffer into a String. The function terminates if it times out (see link:../settimeout[setTimeout()]).

This function is part of the Stream class, and is called by any class that inherits from it (Wire, Serial, etc). See the link:../../stream[Stream class] main page for more information.

[%hardbreaks]


[float]
=== Syntax
`_Serial_.readStringUntil(terminator)`


[float]
=== Parameters
`_Serial_`: serial port object. See the list of available serial ports for each board on the link:../../serial[Serial main page]. +
`terminator` : the character to search for (`char`)

[float]
=== Returns
The entire String read from the serial buffer, up to the terminator character

--
// OVERVIEW SECTION ENDS


// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Notes and Warnings
The terminator character is discarded from the serial buffer.
[%hardbreaks]

--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== See also

[role="language"]
* #LANGUAGE# link:../../serial[Serial]
* #LANGUAGE# link:../begin[begin()]
* #LANGUAGE# link:../end[end()]
* #LANGUAGE# link:../available[available()]
* #LANGUAGE# link:../read[read()]
* #LANGUAGE# link:../peek[peek()]
* #LANGUAGE# link:../flush[flush()]
* #LANGUAGE# link:../print[print()]
* #LANGUAGE# link:../println[println()]
* #LANGUAGE# link:../write[write()]
* #LANGUAGE# link:../serialevent[SerialEvent()]
* #LANGUAGE# link:../../stream/streamparsefloat[stream.parseFloat()]

--
// SEE ALSO SECTION ENDS