---
title: serialEvent()
---




= serialEvent()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Description
Called when data is available. Use `Serial.read()` to capture this data.

`serialEvent()` functionality is not available on all Arduino boards or `_Serial_` interfaces:
[options="header"]
|======================================================
| Board           | Available `serialEvent()` functions
| Uno +
  Nano            | `serialEvent()`
| Mega            | `serialEvent()` +
                    `serialEvent1()` +
                    `serialEvent2()` +
                    `serialEvent3()`
| Leonardo +
  Micro +
  Yún             | `serialEvent1()`
| Uno WiFi Rev2 +
  Nano Every      | None
| MKR boards +
  Nano 33 IoT +
  Zero            | None
| Nano 33 BLE     | None
| Portenta H7     | None
| Due             | `serialEvent()` +
                    `serialEvent1()` +
                    `serialEvent2()` +
                    `serialEvent3()`
| 101             | `serialEvent1()`
|======================================================
[%hardbreaks]


[float]
=== Syntax

[source,arduino]
----
void serialEvent() {
  //statements
}
----
For boards with additional serial ports (see the list of available serial ports for each board on the link:../../serial[Serial main page]):
[source,arduino]
----
void serialEvent1() {
  //statements
}

void serialEvent2() {
  //statements
}

void serialEvent3() {
  //statements
}
----


[float]
=== Parameters
`statements`: any valid statements


[float]
=== Returns
Nothing

--
// OVERVIEW SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== See also

[role="example"]
* #EXAMPLE# http://arduino.cc/en/Tutorial/SerialEvent[Serial Event^]

[role="language"]
* #LANGUAGE# link:../begin[begin()]
* #LANGUAGE# link:../end[end()]
* #LANGUAGE# link:../available[available()]
* #LANGUAGE# link:../read[read()]
* #LANGUAGE# link:../peek[peek()]
* #LANGUAGE# link:../flush[flush()]
* #LANGUAGE# link:../print[print()]
* #LANGUAGE# link:../println[println()]
* #LANGUAGE# link:../write[write()]

--
// SEE ALSO SECTION ENDS
