:source-highlighter: pygments
:pygments-style: arduino
:ext-relative: adoc


= tone()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Description
Generates a square wave of the specified frequency (and 50% duty cycle) on a pin. A duration can be specified, otherwise the wave continues until a call to link:noTone{ext-relative}[noTone()]. The pin can be connected to a piezo buzzer or other speaker to play tones.

Only one tone can be generated at a time. If a tone is already playing on a different pin, the call to tone() will have no effect. If the tone is playing on the same pin, the call will set its frequency.

Use of the `tone()` function will interfere with PWM output on pins 3 and 11 (on boards other than the Mega).

It is not possible to generate tones lower than 31Hz. For technical details, see https://code.google.com/p/rogue-code/wiki/ToneLibraryDocumentation#Ugly_Details[Brett Hagman's notes].
[%hardbreaks]


[float]
=== Syntax
`tone(pin, frequency)`

`tone(pin, frequency, duration)`
[%hardbreaks]

[float]
=== Parameters
`pin`: the pin on which to generate the tone

`frequency`: the frequency of the tone in hertz - `unsigned int`

`duration`: the duration of the tone in milliseconds (optional) - `unsigned long`
[%hardbreaks]

[float]
=== Returns
Nothing

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Notes and Warnings
If you want to play different pitches on multiple pins, you need to call `noTone()` on one pin before calling `tone() on the next pin.
[%hardbreaks]

[float]
=== See also
// Link relevant content by category, such as other Reference terms (please add the tag #LANGUAGE#),
// definitions (please add the tag #DEFINITION#), and examples of Projects and Tutorials
// (please add the tag #EXAMPLE#)  ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄

[role="language"]
* #LANGUAGE# link:noTone{ext-relative}[noTone()] +
* #LANGUAGE# link:analogWrite{ext-relative}[analogWrite()] 

[role="example"]
* #EXAMPLE# http://arduino.cc/en/Tutorial/Tone[Tone^] +
* #EXAMPLE# http://arduino.cc/en/Tutorial/Tone[Pitch follower^] +
* #EXAMPLE# http://arduino.cc/en/Tutorial/Tone3[Simple Keyboard^] +
* #EXAMPLE# http://arduino.cc/en/Tutorial/Tone4[multiple tones^] +
* #EXAMPLE# http://arduino.cc/en/Tutorial/PWM[PWM^]

--
// HOW TO USE SECTION ENDS
